# docker-compose.yml
services:
  # 서비스명
  app:
    # .(현재폴더)에 있는 도커파일 사용하여 이미지 빌드
    build: .
    # HOST : CONTAINER
    ports:
      - '3001:3001'
    # 환경변수파일 사용
    env_file:
      - .env
    # npm start
    command: ['npm', 'start']
#원격 DB가 있으므로 도커에 DB를 안띄움 >> 필요없음

# depends_on:
#   - db

#
# 컨테이너 안에 DB띄우기
# db:
#   image: mysql:8.0.42
#   restart: always
#   environment:
#     MYSQL_ROOT_PASSWORD: 1234
#     TZ: Asia/Seoul
#   # 초기 sql 스크립트 마운트하여 한번만 실행
#   volumes:
#     - ./nodejs_db.sql:/docker-entrypoint-initdb.d/nodejs_db.sql
#   # 로컬 db가 3306이므로 로컬 3307을 통해 컨테이너 내부 3306으로 접속
#   ports:
#     - '3307:3306'
#   # HOST (db tool) : CONTAINER (maria in docker)
